CREATE PROCEDURE FI_SP_ConsBeneficiarioPorCPF
    @CPF VARCHAR(11)
AS
BEGIN
    SET NOCOUNT ON;

IF(@CPF IS NULL OR LTRIM(RTRIM(@CPF)) = '')
    BEGIN
        SELECT NOME, CPF, IDCLIENTE, ID 
        FROM BENEFICIARIOS WITH(NOLOCK);
END
ELSE
    BEGIN
        SELECT NOME, CPF, IDCLIENTE, ID 
        FROM BENEFICIARIOS WITH(NOLOCK) 
        WHERE CPF = @CPF;
END
END
